# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 27007b89d37d6fe676c6f39884dccd98b8de7d1f16e1ca4b35f3c369de55ee846ead3ad281d33cd09c32769e8e75342feb0361ba1d0ca20d327d4abb90ff052e

test:
  secret_key_base: de3a643be1211a33ee3cce885eeedc5c949178204f0628038ec93c027bd53f096a7eef2d8f0c159065803607029326a098861233f5ecdec0276b1fb88973b3ff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
